#!/bin/sh
set -e
# Automatically added by dh_pycentral
if which pycentral >/dev/null 2>&1; then
	pycentral pkginstall ftputil
	if grep -qs '^ftputil$' /var/lib/pycentral/delayed-pkgs; then
		sed -i '/^ftputil$/d' /var/lib/pycentral/delayed-pkgs
	fi
fi
# End automatically added section
