#!/bin/sh
set -e
# Automatically added by dh_pycentral
if which pycentral >/dev/null 2>&1 && pycentral --help 2>/dev/null | grep -q '^ *version'; then
	pycentral pkgprepare ftputil <<PYEOF
[python-package]
format = 1
python-version = >= 2.3
[pycentral]
version = 0.6.7
[files]
/usr/share/pyshared/ftputil-2.3.egg-info=f
/usr/share/pyshared/ftputil=d
/usr/share/pyshared/ftputil/ftp_stat.py=f
/usr/share/pyshared/ftputil/_test_ftputil.py=f
/usr/share/pyshared/ftputil/ftputil.py=f
/usr/share/pyshared/ftputil/_test_base.py=f
/usr/share/pyshared/ftputil/ftputil.txt=f
/usr/share/pyshared/ftputil/lrucache.py=f
/usr/share/pyshared/ftputil/ftp_stat_cache.py=f
/usr/share/pyshared/ftputil/__init__.py=f
/usr/share/pyshared/ftputil/_test_ftp_stat.py=f
/usr/share/pyshared/ftputil/ftp_error.py=f
/usr/share/pyshared/ftputil/_test_ftp_path.py=f
/usr/share/pyshared/ftputil/ftp_file.py=f
/usr/share/pyshared/ftputil/ftputil.html=f
/usr/share/pyshared/ftputil/_test_ftp_stat_cache.py=f
/usr/share/pyshared/ftputil/ftputil_version.py=f
/usr/share/pyshared/ftputil/README.txt=f
/usr/share/pyshared/ftputil/_mock_ftplib.py=f
/usr/share/pyshared/ftputil/ftp_path.py=f
/usr/share/pyshared/ftputil/README.html=f
PYEOF
else
	mkdir -p /var/lib/pycentral
	echo ftputil >> /var/lib/pycentral/delayed-pkgs
fi
# End automatically added section
